ALTER SYSTEM SET SGA_TARGET = 500M SCOPE = BOTH;
/
ALTER SYSTEM SET PGA_AGGREGATE_TARGET = 200M SCOPE = BOTH;
/
ALTER PLUGGABLE DATABASE thurs_27328_Irene_EmergencyTracker_DB ARCHIVELOG;
/
ALTER SYSTEM SET UNDO_RETENTION = 900 SCOPE = BOTH;
/
