CREATE PLUGGABLE DATABASE thurs_27328_Irene_EmergencyTracker_DB
ADMIN USER pdb_admin IDENTIFIED BY Irene
ROLES = (DBA)
FILE_NAME_CONVERT = (
    'C:\APP\HP\PRODUCT\21C\ORADATA\XE\PDBSEED\',
    'C:\APP\HP\PRODUCT\21C\ORADATA\XE\thurs_27328_Irene_EmergencyTracker_DB\'
);
/
ALTER PLUGGABLE DATABASE thurs_27328_Irene_EmergencyTracker_DB OPEN;
/
ALTER SESSION SET CONTAINER = thurs_27328_Irene_EmergencyTracker_DB;
/
