CREATE TABLESPACE emergency_data_ts
DATAFILE 'C:\APP\HP\PRODUCT\21C\ORADATA\XE\thurs_27328_Irene_EmergencyTracker_DB\emergency_data01.dbf'
SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
/
CREATE TABLESPACE emergency_index_ts
DATAFILE 'C:\APP\HP\PRODUCT\21C\ORADATA\XE\thurs_27328_Irene_EmergencyTracker_DB\emergency_index01.dbf'
SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
/
CREATE TEMPORARY TABLESPACE emergency_temp_ts
TEMPFILE 'C:\APP\HP\PRODUCT\21C\ORADATA\XE\thurs_27328_Irene_EmergencyTracker_DB\emergency_temp01.dbf'
SIZE 50M AUTOEXTEND ON NEXT 25M MAXSIZE 200M;
/
