GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE MATERIALIZED VIEW,
      CREATE DATABASE LINK, CREATE TYPE TO pdb_admin;
/
GRANT UNLIMITED TABLESPACE TO pdb_admin;
/
GRANT EXECUTE ANY PROCEDURE, SELECT ANY DICTIONARY TO pdb_admin;
/
GRANT ALTER ANY TABLE, DROP ANY TABLE, INSERT ANY TABLE,
      UPDATE ANY TABLE, DELETE ANY TABLE, SELECT ANY TABLE TO pdb_admin;
/
