CREATE TABLE wards (
    ward_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ward_name   VARCHAR2(50) NOT NULL UNIQUE,
    total_beds  NUMBER NOT NULL CHECK (total_beds > 0),
    CONSTRAINT pk_wards PRIMARY KEY (ward_id)
) TABLESPACE emergency_data_ts;

CREATE TABLE beds (
    bed_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ward_id  NUMBER NOT NULL,
    status   VARCHAR2(10) DEFAULT 'Available',
    CONSTRAINT pk_beds PRIMARY KEY (bed_id),
    CONSTRAINT fk_beds_ward FOREIGN KEY (ward_id)
        REFERENCES wards(ward_id),
    CONSTRAINT chk_bed_status CHECK (status IN ('Available','Occupied'))
) TABLESPACE emergency_data_ts;

CREATE INDEX idx_beds_ward
ON beds(ward_id)
TABLESPACE emergency_index_ts;

CREATE TABLE patients (
    patient_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name    VARCHAR2(100) NOT NULL,
    category     VARCHAR2(20) CHECK (category IN ('Emergency','Regular')),
    CONSTRAINT pk_patients PRIMARY KEY (patient_id)
) TABLESPACE emergency_data_ts;

CREATE TABLE admissions (
    admission_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id      NUMBER NOT NULL,
    bed_id          NUMBER NOT NULL,
    admission_date  DATE DEFAULT SYSDATE,
    discharge_date  DATE,
    CONSTRAINT pk_admissions PRIMARY KEY (admission_id),
    CONSTRAINT fk_adm_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),
    CONSTRAINT fk_adm_bed FOREIGN KEY (bed_id)
        REFERENCES beds(bed_id),
    CONSTRAINT chk_discharge_date CHECK (discharge_date IS NULL 
            OR discharge_date >= admission_date)
) TABLESPACE emergency_data_ts;




